export const headcountData = [
  { name: 'Condé Nast', Apprentice: 1, Junior: 1, Senior: 3, Lead: 2 },
  { name: 'NYMAG', Apprentice: 1, Junior: 2, Senior: 1, Lead: 2 },
  { name: 'IntellISys', Apprentice: 1, Junior: 1, Senior: 4, Lead: 2 },
  { name: 'FoundEra', Apprentice: 1, Junior: 3, Senior: 5, Lead: 2 },
  { name: 'New York Times', Apprentice: 1, Junior: 2, Senior: 4, Lead: 1 },
];

export const organizationalClimate = [
  {
    subject: 'Compensación ',
    A: (Math.random() * 100).toFixed(2),
    B: (Math.random() * 100).toFixed(2),
    C: (Math.random() * 100).toFixed(2),
    fullMark: 100,
  },
  {
    subject: 'Respeto',
    A: (Math.random() * 100).toFixed(2),
    B: (Math.random() * 100).toFixed(2),
    C: (Math.random() * 100).toFixed(2),
    fullMark: 100,
  },
  {
    subject: 'Desarrollo profesional',
    A: (Math.random() * 100).toFixed(2),
    B: (Math.random() * 100).toFixed(2),
    C: (Math.random() * 100).toFixed(2),
    fullMark: 100,
  },
  {
    subject: 'Comunicación ',
    A: (Math.random() * 100).toFixed(2),
    B: (Math.random() * 100).toFixed(2),
    C: (Math.random() * 100).toFixed(2),
    fullMark: 100,
  },
  {
    subject: 'Planificación y toma de decisiones',
    A: (Math.random() * 100).toFixed(2),
    B: (Math.random() * 100).toFixed(2),
    C: (Math.random() * 100).toFixed(2),
    fullMark: 100,
  },
  {
    subject: 'Entrenamiento y aprendizaje',
    A: (Math.random() * 100).toFixed(2),
    B: (Math.random() * 100).toFixed(2),
    C: (Math.random() * 100).toFixed(2),
    fullMark: 100,
  },
  {
    subject: 'Innovación Compromiso ',
    A: (Math.random() * 100).toFixed(2),
    B: (Math.random() * 100).toFixed(2),
    C: (Math.random() * 100).toFixed(2),
    fullMark: 100,
  },
  {
    subject: 'Relaciones',
    A: (Math.random() * 100).toFixed(2),
    B: (Math.random() * 100).toFixed(2),
    C: (Math.random() * 100).toFixed(2),
    fullMark: 100,
  },
  {
    subject: 'Manejo de conflictos',
    A: (Math.random() * 100).toFixed(2),
    B: (Math.random() * 100).toFixed(2),
    C: (Math.random() * 100).toFixed(2),
    fullMark: 100,
  },
  {
    subject: 'Trabajo en equipo ',
    A: (Math.random() * 100).toFixed(2),
    B: (Math.random() * 100).toFixed(2),
    C: (Math.random() * 100).toFixed(2),
    fullMark: 100,
  },
  {
    subject: 'Calidad de servicio',
    A: (Math.random() * 100).toFixed(2),
    B: (Math.random() * 100).toFixed(2),
    C: (Math.random() * 100).toFixed(2),
    fullMark: 100,
  },
  {
    subject: 'Dirección ',
    A: (Math.random() * 100).toFixed(2),
    B: (Math.random() * 100).toFixed(2),
    C: (Math.random() * 100).toFixed(2),
    fullMark: 100,
  },
  {
    subject: 'Claridad de rol ',
    A: (Math.random() * 100).toFixed(2),
    B: (Math.random() * 100).toFixed(2),
    C: (Math.random() * 100).toFixed(2),
    fullMark: 100,
  },
];
